base = int(input("Qual a tabuada quer ver? "))
tab1 = base * 1
print("Tabuada de {} -> {} X 1 = {}".format(base,base, tab1))
tab2 = base * 2
print("Tabuada de {} -> {} X 2 = {}".format(base,base,tab2))
tab3 = base * 3
print("Tabuada de {} -> {} X 3 = {}".format(base,base,tab3))
tab4 = base * 4
print("Tabuada de {} -> {} X 4 = {}".format(base,base,tab4))
tab5 = base * 5
print("Tabuada de {} -> {} X 5 = {}".format(base,base,tab5))
tab6 = base * 6
print("Tabuada de {} -> {} X 6 = {}".format(base,base,tab6))
tab7 = base * 7
print("Tabuada de {} -> {} X 7 = {}".format(base,base,tab7))
tab8 = base * 8
print("Tabuada de {} -> {} X 8 = {}".format(base,base,tab8))
tab9 = base * 9
print("Tabuada de {} -> {} X 9 = {}".format(base,base,tab9))
tab10 = base * 10
print("Tabuada de {} -> {} X 10 = {}".format(base,base,tab10))
